apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: default
spec:
  collectors:
    - logs:
        collectorName: nginx
        name: default/nginx
        selector:
          - app: nginx
    - exec:
        collectorName: dnsutils
        command:
          - ping -c 5 www.yahoo.com
        containerName: dnsutils
        name: default/dnsutils
        selector:
          - app=dnsutils
        timeout: 10s
