apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: default
spec:
  collectors:
    - exec:
        collectorName: dnsutils
        command:
          - ping -c 100 www.yahoo.com
        containerName: dnsutils
        name: default/dnsutils
        selector:
          - app=dnsutils
        timeout: 10s
    - logs:
        collectorName: dnsutils
        name: default/dnsutils
        selector:
          - app=nginx
    - copyFromHost:
        collectorName: dagr-copy
        name: mega
        command: "ls -al"
        hostPath: /etc/hosts >> /tmp/dagr.hosts
        extractArchive: true
        image: alpine
        imagePullPolicy: IfNotPresent
        timeout: 1m
